### ISSUE TITLE
Fix Input Validation on company Settings 

### ISSUE THREAD

**Issue by dineshbizsoft** [bizsoftsolution/AccountBuddy#1]
please fix all input fields validation on **company settings**

**Comment by PrasathBizSoft** [comment]
Noted and fixed
# `![bg](https://cloud.githubusercontent.com/assets/28782631/26203682/d0771868-3bf9-11e7-8c07-44fd149bfa28.jpg)`

**Comment by PrasathBizSoft** [comment]
bug fixed
![bg](https://cloud.githubusercontent.com/assets/28782631/26203763/1ef6cfb0-3bfa-11e7-8643-2203722e83f1.jpg)

**Comment by dineshbizsoft** [comment]
ok
